launcher-csharp/Admin/Controllers/Eg01CreateUserController.cs
using DocuSign.CodeExamples.Common;
using DocuSign.CodeExamples.Controllers;
using DocuSign.CodeExamples.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using DocuSign.CodeExamples.Admin.Examples;
using DocuSign.Admin.Client;
using System;

namespace DocuSign.CodeExamples.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/Eg01")]
    public class Eg01CreateUserController: EgController
    {
        public Eg01CreateUserController(
            DSConfiguration dsConfig,
            IRequestItemsService requestItemsService)
            : base(dsConfig, requestItemsService)
        {
        }

        public override string EgName => "Eg01";

        protected override void InitializeInternal()
        {
            try
            {
                var accessToken = RequestItemsService.User.AccessToken;
                var basePath = RequestItemsService.Session.BasePath + "/restapi";
                var accountId = RequestItemsService.Session.AccountId;

                var (permissionProfiles, groups) = CreateUser.GetPermissionProfilesAndGroups(accessToken, basePath, accountId);

                ViewBag.PermissionProfiles = permissionProfiles.PermissionProfiles;
                ViewBag.Groups = groups.Groups;
            }
            catch (ApiException apiException)
            {
                ViewBag.errorCode = apiException.ErrorCode;
                ViewBag.errorMessage = apiException.Message;
            }
        }

        [MustAuthenticate]
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string email, string firstName, string lastName, string userName, string permissionProfileId, string groupId)
        {
            // Obtain your OAuth token
            var accessToken = RequestItemsService.User.AccessToken;
            var basePath = RequestItemsService.Session.AdminApiBasePath;
            var accountId = RequestItemsService.Session.AccountId;
            var organizationId = RequestItemsService.OrganizationId;

            try
            {
                // Call the Admin API to create a new user
                var user = CreateUser.CreateNewUser(accessToken, basePath, Guid.Parse(accountId), 
                    organizationId, firstName, lastName, userName, email, Int64.Parse(permissionProfileId), Int64.Parse(groupId));

                //Show results
                ViewBag.h1 = "Create a new eSignature user";
                ViewBag.message = "Results from Users::addUsers method:";
                ViewBag.Locals.Json = JsonConvert.SerializeObject(user, Formatting.Indented);

                return View("example_done");
            }
            catch (ApiException apiException)
            {
                ViewBag.errorCode = apiException.ErrorCode;
                ViewBag.errorMessage = apiException.Message;

                return View("Error");
            }
        }
    }
}

launcher-csharp/Admin/Views/Eg01CreateUser/Eg01.cshtml
@*@model DocuSign.CodeExamples.Admin.Controllers.Eg01CreateUserController*@

<h4>1. Create a new active eSignature user</h4>
<p>
    Demonstrates how to create a new eSignature user and activate their account automatically.
</p>

@if (ViewBag.showDoc == true)
{
    <p><a target='_blank' href='<%= documentation %>'>Documentation</a> about this example.</p>
}

<p>
    API method used:
    <a target='_blank' href="https://developers.docusign.com/docs/admin-api/reference/users/users/createuser/">Users::createUser</a>.
</p>

<p>
    View source file <a target="_blank" href="@ViewBag.source">Eg01CreateUserController.cs</a> on GitHub.
</p>

<form class="eg" asp-action="Create" asp-controller="Eg01CreateUser" asp-area="Admin" method="post" data-busy="form">
    <div class="form-group">
        <label for="userName">User Name</label>
        <input type="text" class="form-control" id="userName" placeholder="PatJohnson" name="userName"
               required>
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" placeholder="Pat" name="firstName"
               required>
    </div>
    <div class="form-group">
        <label for="lastName">Last Name</label>
        <input type="text" class="form-control" id="lastName" placeholder="Johnson" name="lastName"
               required>
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email"
               aria-describedby="emailHelp" placeholder="pat@example.com" required>
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="PermissionProfiles">eSignature permission profile</label>
        @Html.DropDownList("PermissionProfileId", new SelectList(ViewBag.PermissionProfiles, "PermissionProfileId", "PermissionProfileName"), new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="DSGroups">DocuSign Admin group</label>
        @Html.DropDownList("GroupId", new SelectList(ViewBag.Groups, "GroupId", "GroupName"), new { @class = "form-control" })
    </div>
    <input type="hidden" name="_csrf" value="<%- csrfToken %>">
    <button type="submit" class="btn btn-primary">Submit</button>
</form>