launcher-csharp/Admin/Controllers/Eg03BulkExportUserDataController.cs
using DocuSign.CodeExamples.Common;
using DocuSign.CodeExamples.Controllers;
using DocuSign.CodeExamples.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using DocuSign.CodeExamples.Admin.Examples;
using DocuSign.Admin.Client;
using System.IO;

namespace DocuSign.CodeExamples.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/Eg03")]
    public class Eg03BulkExportUserDataController : EgController
    {
        public Eg03BulkExportUserDataController(
            DSConfiguration dsConfig,
            IRequestItemsService requestItemsService)
            : base(dsConfig, requestItemsService)
        {
        }

        public override string EgName => "Eg03";

        [MustAuthenticate]
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create()
        {
            // Obtain your OAuth token
            var accessToken = RequestItemsService.User.AccessToken;
            var basePath = RequestItemsService.Session.AdminApiBasePath;
            var organizationId = RequestItemsService.OrganizationId;
            var filePath = Path.GetFullPath(Path.Combine(
                Path.GetFullPath(System.AppDomain.CurrentDomain.BaseDirectory),
                Config.exportUsersPath));

            try
            {
                // Call the Admin API to create a new user
                var organizationExportsResponse = BulkExportUserData.CreateBulkExportRequest(
                    accessToken, basePath, organizationId, filePath);

                //Show results
                ViewBag.h1 = "Bulk export user data";
                ViewBag.message = $"User data exported to {filePath}. Results from UserExport:getUserListExport method:";
                ViewBag.Locals.Json = JsonConvert.SerializeObject(organizationExportsResponse, Formatting.Indented);

                return View("example_done");
            }
            catch (ApiException apiException)
            {
                ViewBag.errorCode = apiException.ErrorCode;
                ViewBag.errorMessage = apiException.Message;

                return View("Error");
            }
        }
    }
}

launcher-csharp/Admin/Views/Eg03BulkExportUserData/Eg03.cshtml
<h4>3. Bulk export user data</h4>
<p>
    Demonstrates how to bulk export user accounts within an organization into a CSV (comma-separated value) file.
</p>

 @if (ViewBag.showDoc == true)
 {
     <p><a target='_blank' href='<%= documentation %>'>Documentation</a> about this example.</p>
 }

<p>
    API methods used:
    <a target='_blank' href="https://developers.docusign.com/docs/admin-api/reference/bulkoperations/userexport/createuserlistexport/">UserExport::createUserListExport</a>,  
    <a target='_blank' href="https://developers.docusign.com/docs/admin-api/reference/bulkoperations/userexport/getuserlistexport/">UserExport::getUserListExport</a>.
</p>

<p>
    View source file <a target="_blank" href="@ViewBag.source">Eg03BulkExportUserDataController.cs</a> on GitHub.
</p>

<form class="eg" asp-action="Create" asp-controller="Eg03BulkExportUserData" asp-area="Admin" method="post" data-busy="form">
    <input type="hidden" name="_csrf" value="<%- csrfToken %>">
    <button type="submit" class="btn btn-primary">Submit</button>
</form>